//
// Copyright (c) 2019 Takpit. All rights reserved.
//

#ifndef PROTO_NMEA_PROTOCOLFORMAT_H
#define PROTO_NMEA_PROTOCOLFORMAT_H

#ifdef __cplusplus
extern "C"
{
#endif

#define PROTOCOL_START_CHAR '$'
#define PROTOCOL_FIELD_DELIMITER ','
#define PROTOCOL_DATA_START_INDEX 1

#define TALKER_ID_MIN_LENGTH 2
#define TALKER_ID_MAX_LENGTH 3

#define MESSAGE_TYPE_LENGTH 3

#define MESSAGE_DATA_START_INDEX PROTOCOL_DATA_START_INDEX + TALKER_ID_MIN_LENGTH + MESSAGE_TYPE_LENGTH

#ifdef __cplusplus
}
#endif

#endif //PROTO_NMEA_PROTOCOLFORMAT_H
