//
// Copyright (c) 2019 Takpit. All rights reserved.
//

#ifndef PROTO_NMEA_PROTOCOLFORMAT_H
#define PROTO_NMEA_PROTOCOLFORMAT_H

#ifdef __cplusplus
extern "C"
{
#endif

#define PROTOCOL_START_CHAR '$'
#define PROTOCOL_STOP_CHAR_1 '\r'
#define PROTOCOL_STOP_CHAR_2 '\n'
#define PROTOCOL_FIELD_DELIMITER ','
#define PROTOCOL_CHECKSUM_DELIMITER '*'

#define PROTOCOL_START_LENGTH 1
#define PROTOCOL_STOP_LENGTH 2

#define CHECKSUM_DELIMITER_LENGTH 1
#define CHECKSUM_DATA_LENGTH 2
#define CHECKSUM_FULL_LENGTH (CHECKSUM_DATA_LENGTH + CHECKSUM_DELIMITER_LENGTH)

#define MESSAGE_MIN_LENGTH 10
#define MESSAGE_MAX_LENGTH 90

#define PROTOCOL_DATA_START_INDEX 1

#define TALKER_ID_MIN_LENGTH 2
#define TALKER_ID_MAX_LENGTH 3

#define MESSAGE_ID_LENGTH 3

#define MESSAGE_TYPE_MIN_LENGTH (TALKER_ID_MIN_LENGTH + MESSAGE_ID_LENGTH)
#define MESSAGE_TYPE_MAX_LENGTH (TALKER_ID_MAX_LENGTH + MESSAGE_ID_LENGTH)

#define MESSAGE_DATA_START_INDEX (PROTOCOL_DATA_START_INDEX + TALKER_ID_MIN_LENGTH + MESSAGE_ID_LENGTH)

#ifdef __cplusplus
}
#endif

#endif //PROTO_NMEA_PROTOCOLFORMAT_H
