#ifndef PROTO_NMEA_ERRORS
#define PROTO_NMEA_ERRORS

enum general_errors
{
    EVALID = 0,
    ENULL_STRING
};

enum parser_errors
{
    EINVALID_PROTOCOL_BEGINNING = 90,
    EINVALID_PROTOCOL_ENDING,
    ESHORT_MESSAGE,
    ELONG_MESSAGE,
    EINVALID_CHECKSUM,
    EMISSING_CHECKSUM,
    EMISSING_CHECKSUM_DATA,
    EUNMATCHING_CHECKSUM,
    EINVALID_MESSAGE_TYPE
};

#endif
